# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from functools import partial
from db_requests import db


class Ui_Form(object):
    def __init__(self, id):
        self.id = id

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(60, 30, 300, 200))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.gen_table(self.tableWidget)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Заказ"))

    def gen_table(self, widget):
        """
        Generating table with database content
        :param widget: tableWidget to generate
        """
        table_colums = ['Название', 'Количество', 'Цена', 'Итог']
        bridge_id = db.get_items('Bridge', str(self.id), 'order_id')[0][0]
        listy = db.get_items('Goods_list', str(bridge_id), 'group_id')
        goods = db.get_items('Goods', tuple([i[1] for i in listy]), 'id')
        # print(goods)
        names_of_goods = [i[1] for i in goods]
        num_of_goods = [i[2] for i in listy]
        price_of_goods = [i[2] for i in goods]
        itog = [num_of_goods[i] * price_of_goods[i] for i in range(len(names_of_goods))]
        # print(bridge_id, listy)
        # print(names_of_goods, num_of_goods)

        table_items = [(names_of_goods[i], num_of_goods[i], price_of_goods[i], itog[i]) for i in range(len(names_of_goods))]
        # print(table_items)
        widget.setColumnCount(len(table_colums))
        widget.setHorizontalHeaderLabels(table_colums)
        widget.horizontalHeader().setDefaultSectionSize(150)
        widget.setRowCount(len(table_items))

        for row in range(widget.rowCount()):
            for col in range(widget.columnCount()):
                widget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeToContents)
                widget.setItem(row, col, QtWidgets.QTableWidgetItem(str(table_items[row][col])))



if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form(2)
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
